/*
 * This source file was generated by the Gradle 'init' task
 */
package io.substrait.dialect;

import com.fasterxml.jackson.core.JsonProcessingException;
import com.fasterxml.jackson.databind.ObjectMapper;
import com.fasterxml.jackson.dataformat.yaml.YAMLFactory;

public class App {
    public int run() throws JsonProcessingException {
        DialectGenerator generator = new DialectGenerator();
        Dialect dialect = generator.generate();
 
        // Serialize to YAML (requires jackson-dataformat-yaml dependency)
        ObjectMapper mapper = new ObjectMapper(new YAMLFactory());
        String yaml = mapper.writeValueAsString(dialect);

        System.out.println(yaml);
        
        return 0;
    }

    public static void main(String[] args) {
        try {
            int returnCode = new App().run();
            System.exit(returnCode);
        } catch (JsonProcessingException e) {
            e.printStackTrace();
            System.exit(1);
        }
    }
}
